TARGET_BOARD_KERNEL_HEADERS := hardware/samsung_slsi/exynos/kernel-$(TARGET_LINUX_KERNEL_VERSION)-headers/kernel-headers
TARGET_SLSI_VARIANT := bsp
TARGET_SOC_NAME := exynos
BOARD_USES_DT := true

# FIMG2D
BOARD_USES_SKIA_FIMGAPI := true
BOARD_USES_FIMGAPI_V5X := true

# Gralloc
BOARD_USES_EXYNOS5_COMMON_GRALLOC := true

# (G)SCALER
BOARD_USES_SCALER := true

# HWComposer
BOARD_USES_VPP := true
BOARD_HDMI_INCAPABLE := true

# HWCServices - requires framework support
BOARD_USES_HWC_SERVICES := true

# Samsung OpenMAX Video
BOARD_USE_STOREMETADATA := true
BOARD_USE_METADATABUFFERTYPE := true
BOARD_USE_DMA_BUF := true
BOARD_USE_ANB_OUTBUF_SHARE := true
BOARD_USE_IMPROVED_BUFFER := true
BOARD_USE_NON_CACHED_GRAPHICBUFFER := true
BOARD_USE_GSC_RGB_ENCODER := true
BOARD_USE_CSC_HW := false
BOARD_USE_QOS_CTRL := false
BOARD_USE_S3D_SUPPORT := true
BOARD_USE_TIMESTAMP_REORDER_SUPPORT := false
BOARD_USE_DEINTERLACING_SUPPORT := true
BOARD_USE_VP8ENC_SUPPORT := true
BOARD_USE_HEVCDEC_SUPPORT := true
BOARD_USE_HEVCENC_SUPPORT := true
BOARD_USE_HEVC_HWIP := false
BOARD_USE_VP9DEC_SUPPORT := true
BOARD_USE_VP9ENC_SUPPORT := false
BOARD_USE_CUSTOM_COMPONENT_SUPPORT := true
BOARD_USE_VIDEO_EXT_FOR_WFD_HDCP := false
BOARD_USE_VIDEO_EXT_FOR_WFD_DRM := false
BOARD_USE_SINGLE_PLANE_IN_DRM := false
BOARD_USES_DEFAULT_CSC_HW_SCALER := true

# Virtual display
BOARD_USES_VDS_BGRA8888 := true
BOARD_USES_VDS_OTHERFORMAT := true
# BOARD_USES_VIRTUAL_DISPLAY := true  -- depends on platform changes
BOARD_USES_VIRTUAL_DISPLAY_DECON_EXT_WB := false
BOARD_VIRTUAL_DISPLAY_DISABLE_IDMA_G0 := false
BOARD_USES_CEC := true

# M2M1Shot
BOARD_USES_SCALER_M2M1SHOT := true
